sudo: false
dist: trusty

language: java
jdk: openjdk8

install: true
script: ./gradlew build

after_success: '[[ "$TRAVIS_BRANCH" = "master" ]] && ./gradlew uploadArchives'

notifications:
  email: false
